language: python
cache:
  directories:
    - $HOME/virtualenv/python3.5.3/
python: 3.5
install:
  - python setup.py develop
  - pip install coveralls
script: coverage run -m unittest discover tests
after_success: coveralls

deploy:
  provider: pypi
  user: serenata
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: master
