language: python
python: 3.5
cache:
  directories:
    - $HOME/virtualenv/python3.5.3/

jobs:
  include:
    - stage: unit
      script: pytest tests/unit

    - stage: journey
      script: travis_wait 40 pytest tests/journey

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: serenata
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          branch: master

install:
  - python setup.py develop
  - pip install coveralls pytest pytest-cov

after_success:
  - coveralls
