language: python
python: 3.5
cache: pip
install:
  - pip install -U pip wheel
  - pip install --requirement=$TRAVIS_BUILD_DIR/requirements.txt
  - pip install coveralls
script: coverage run -m unittest discover tests
after_success: coveralls
